apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
